# Site settings
title: "Hegzcast"
description: "بودكاست عربي يهتم بكل ما هو تقني وعلمي"
podcast-description: "Hegzcast discusses various topics that I find interesting, this can range from topics about my favorite linux distro to topics involving engineering and mathematics."
url:  "https://podcast.hegz.me" # Actual base url of the website
baseurl: "/"                    # url of the jekyll blog. e.g. if you set url to "mysite.com" and baseurl to "blog", the jekyll website will work on "mysite.com/blog"
author:
  name: "Yusuf Hegazy"
  email: "me@hegz.me"
  url: "https://hegz.me"
permalink: pretty
permalink: /:title
keywords: [podcast, hegzploit]

#Plugins
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]

#exclude: [_podcast.rss] #Ignore this, it will be used in case I decide to add rss feed

#Pagination
paginate: 5
paginate_path: "/page-:num/"

#Sass
sass:
  style: compressed
  sourcemap: never

#SEO
twitter:
  username: hegzploit
  card: summary
facebook:
  app_id: 
logo: /assets/img/Podcast_Cover.png
social:
  name: Alessio Franceschi
  links:
    - https://github.com/hegzploit
    - https://twitter.com/hegzploit
    - https://www.linkedin.com/in/yusufhegazy/
lang: it

#Podcast Metadata. Used by the RSS Feed, which currently isn't in use. So you can avoid this
podcast_title: Hegzcast
podcast_author: Yusuf Hegazy
podcast_email: me@hegz.me
podcast_subtitle: "by nerds, for nerds"
podcast_summary: "Podcast oriented on various technology and scientific topics."
podcast_description: "This is my personal podcast where I will be talking about various things I find interesting, I will also try to keep it intersting and have some guests."
podcast_explicit: "no"
podcast_type: serial 
podcast_lang: ar
podcast_launch: "2022-08-08" #Launch date of your podcast
podcast_copyright: "&#xA9;Yusuf Hegazy"
podcast_feed: 
podcast_artwork: "/assets/img/Podcast_Cover.png"
