analytics-id: 
#Pages
pages:
  - {name: 'Episodes', link: 'episodes.html'}

social:
  - {icon: 'twitter', type: "brand", link: 'https://twitter.com/hegzploit'}
  - {icon: 'envelope', type: "solid", link: 'mailto:me@hegz.me'}
  - {icon: 'rss', type: "solid", link: "#"}

websites-podcast:
  - {name: 'Apple Podcast', link: '#'}
  - {name: 'Spotify', link: '#'}
  - {name: 'YouTube', link: '#'}
  - {name: 'Android', link: '#'}
  - {name: 'Spreaker', link: '#'}
  - {name: 'Google Podcast', link: '#'}
  - {name: 'Anchor', link: '#'}
  - {name: 'Castbox', link: '#'}
  - {name: 'Overcast', link: '#'}
  - {name: 'RadioPublic', link: '#'}
  - {name: 'Breaker', link: '#'}  
  - {name: 'RSS', link: '#'}

translate-date: true #See _includes/date.html to translate the months' name
shownotes: true

#Disqus
disqus:
  disqus_shortname: 
